# Generated by Django 4.1.5 on 2023-01-25 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_alter_sheetsales_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sheetalerts',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sheetsales',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='sheetstock',
            name='created_at',
        ),
    ]
