# Generated by Django 4.1.5 on 2023-01-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_remove_sheetalerts_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chain_name', models.CharField(max_length=64)),
                ('sub_chain_name', models.CharField(max_length=64)),
                ('family_name', models.CharField(max_length=64)),
                ('trademark_name', models.CharField(max_length=64)),
                ('sales_current_month', models.FloatField(default=0)),
                ('sales_compare_month', models.FloatField(default=0)),
                ('sales_variation', models.FloatField(default=0)),
                ('sales_growth', models.FloatField(default=0)),
                ('sales_lost', models.FloatField(default=0)),
                ('sales_month_projection', models.FloatField(default=0)),
                ('stock', models.FloatField(default=0)),
                ('daily_average', models.FloatField(default=0)),
                ('stock_days', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'b2b_report',
            },
        ),
        migrations.AlterField(
            model_name='sheetsales',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sheetstock',
            name='stock_total',
            field=models.FloatField(default=0),
        ),
    ]
