# Generated by Django 4.1.5 on 2023-02-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0006_remove_b2breport_sales_growth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='b2breport',
            name='sales_compare_month',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='b2breport',
            name='sales_lost',
            field=models.FloatField(default=0, null=True),
        ),
    ]
