FROM postgres:latest
RUN apt-get update && apt-get install -y postgresql postgresql-contrib
ENV POSTGRES_PASSWORD=postgres
ENV POSTGRES_USER=postgres
ENV POSTGRES_DB=postgres
EXPOSE 5432
CMD ["postgres"]